name: Promote Cosmos DB documents
on:
    workflow_dispatch:
jobs:
  call-promote-documents-qa:
    name: Promote Documents from DEV to QA
    uses: ./.github/workflows/promote-documents.yml
    with:
      source: DEV
      target: QA
    secrets: inherit
  call-promote-documents-stage:
    name: Promote Documents from QA to STAGE
    needs: call-promote-documents-qa
    uses: ./.github/workflows/promote-documents.yml
    with:
      source: QA
      target: STAGE
    secrets: inherit
  call-promote-documents-prod:
    name: Promote Documents from STAGE to PROD
    needs: call-promote-documents-stage
    uses: ./.github/workflows/promote-documents.yml
    with:
      source: STAGE
      target: PROD
    secrets: inherit
