name: Promote Cosmos DB documents reusable workflow
on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  promote_documents:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:

      - name: Set the source and target table secret names
        run: |
          echo "COSMOSDB_CONNECTION_STRING_SOURCE_NAME=COSMOSDB_CONNECTION_STRING_${{ inputs.source }}" >> $GITHUB_ENV
          echo "COSMOSDB_DATABASE_NAME_SOURCE_NAME=COSMOSDB_DATABASE_NAME_${{ inputs.source }}" >> $GITHUB_ENV
          echo "COSMOSDB_IG_DOCS_TABLE_NAME_SOURCE_NAME=COSMOSDB_IG_DOCS_TABLE_NAME_${{ inputs.source }}" >> $GITHUB_ENV
          echo "BLOB_URL_SOURCE_NAME=BLOB_URL_${{ inputs.source }}" >> $GITHUB_ENV
          echo "COSMOSDB_CONNECTION_STRING_TARGET_NAME=COSMOSDB_CONNECTION_STRING_${{ inputs.target }}" >> $GITHUB_ENV
          echo "COSMOSDB_DATABASE_NAME_TARGET_NAME=COSMOSDB_DATABASE_NAME_${{ inputs.target }}" >> $GITHUB_ENV
          echo "COSMOSDB_IG_DOCS_TABLE_NAME_TARGET_NAME=COSMOSDB_IG_DOCS_TABLE_NAME_${{ inputs.target }}" >> $GITHUB_ENV
          echo "BLOB_URL_TARGET_NAME=BLOB_URL_${{ inputs.target }}" >> $GITHUB_ENV

      - name: Set the source and target table argument values
        run: |
          echo "COSMOSDB_CONNECTION_STRING_SOURCE=${{ secrets[env.COSMOSDB_CONNECTION_STRING_SOURCE_NAME]}}" >> $GITHUB_ENV
          echo "COSMOSDB_DATABASE_NAME_SOURCE=${{ vars[env.COSMOSDB_DATABASE_NAME_SOURCE_NAME]}}" >> $GITHUB_ENV
          echo "COSMOSDB_IG_DOCS_TABLE_NAME_SOURCE=${{ vars[env.COSMOSDB_IG_DOCS_TABLE_NAME_SOURCE_NAME]}}" >> $GITHUB_ENV
          echo "BLOB_URL_SOURCE=${{ vars[env.BLOB_URL_SOURCE_NAME]}}" >> $GITHUB_ENV
          echo "COSMOSDB_CONNECTION_STRING_TARGET=${{ secrets[env.COSMOSDB_CONNECTION_STRING_TARGET_NAME]}}" >> $GITHUB_ENV
          echo "COSMOSDB_DATABASE_NAME_TARGET=${{ vars[env.COSMOSDB_DATABASE_NAME_TARGET_NAME]}}" >> $GITHUB_ENV
          echo "COSMOSDB_IG_DOCS_TABLE_NAME_TARGET=${{ vars[env.COSMOSDB_IG_DOCS_TABLE_NAME_TARGET_NAME]}}" >> $GITHUB_ENV
          echo "BLOB_URL_TARGET=${{ vars[env.BLOB_URL_TARGET_NAME]}}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Promote Documents Script
        run: |
          python promote_documents.py \
            -cs "${{ env.COSMOSDB_CONNECTION_STRING_SOURCE }}" \
            -ds ${{ env.COSMOSDB_DATABASE_NAME_SOURCE }} \
            -ts ${{ env.COSMOSDB_IG_DOCS_TABLE_NAME_SOURCE }} \
            -bs ${{ env.BLOB_URL_SOURCE }} \
            -ct "${{ env.COSMOSDB_CONNECTION_STRING_TARGET }}" \
            -dt ${{ env.COSMOSDB_DATABASE_NAME_TARGET }} \
            -tt ${{ env.COSMOSDB_IG_DOCS_TABLE_NAME_TARGET }} \
            -bt ${{ env.BLOB_URL_TARGET }} \
